### ISSUE TITLE
Unable to access /institutions endpoint

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#27]
@Anakin100100 idk if I'm doing things correcly but I cannot access /institutions endpoint, browser shows `ERR_CONNECTION_REFUSED`. 

I'm on latest master, running app inside docker. I can access /api-docs, so I would expect that is not docker's fault.

U have any idea?

**Comment by Anakin100100** [comment]
This is probably sth related to the production config. Rails has completely separate configs for test development production enviorements and We haven't touched it really so there may be some things that should have been adjusted.

**Comment by micorix** [comment]
afaik rails in docker run in prod mode?

**Comment by Anakin100100** [comment]
@micorix  the issue is resolved. We didn't configure the aproprate variables in the production database config. Please take a look at the pull request I just created. 

Before you start the container you have to first create the database and run all migrations. I don't think you have the required tools locally so start the interactive session to the container with  
docker run --rm -it --entrypoint bash --network host -e DATABASE_PASSWORD=<actual production database password> <docker image id> 

and on the contaienr run 

RAILS_ENV=production bundle exec rake db:create db:migrate. 

Only then can you start the server as usual. You can confirm that everything is working by running a get request against the /institutions endpoint which should return an empty array and code 200 but you have to populate the database using the instructions from the docs. 

You can populate the database from the container becuase all of the tooling is available there. you can start from the Start the job to create the institution types ... part.

**Comment by micorix** [comment]
Thanks for the quick reply! Ok, got it, I will try it.

How about using and entrypoint which would invoke migration script and start the server? That way we wouldn't have to init db manually.

**Comment by micorix** [comment]
@Anakin100100  bump

**Comment by Anakin100100** [comment]
I don't think that entrypoint is an appropriate place to put that code because it would be run every time the container image is spun up and it could result in database clearing in production. The manual way of doing it allows us to make sure that everything works on another database before we only make a switch in the config for a new release

**Comment by micorix** [comment]
Sry, I forgot we agreed on running migrations scripts in gh actions

**Comment by Anakin100100** [comment]
@wojtodzio @micorix I think that we should finish this integration by doing a triple pair programming and we should be done with it within two hours. This way we will be able to finish it there and not wait for another one line mistake that could have been fixed by one of the ruby devs. What do you think about it?

**Comment by micorix** [comment]
@Anakin100100 thanks for following up on the issue.

I don't think my attendance would be helpful/needed for solving the problem though. I started the container and ran the command you mentioned above (`RAILS_ENV=production bundle exec rake db:create db:migrate`). I got the following error:
```
could not translate host name "production_database_address" to address: No address associated with hostname
```

We need to deploy the API ASAP. In order to do that, I need instructions (for both server AND CI runner) on how to connect to db from within the docker container. It would be good to have all this info in docs.

Can we source db creds from env vars?

@Anakin100100 lmk what you think and when you can provide all necessary info

**Comment by Anakin100100** [comment]
@micorix are you using master or the fix branch? I think i changed that already. Because this is an itegration issue we should pair program it. Are you free this afternoon? @wojtodzio your presence would be highly benefitial.

**Comment by micorix** [comment]
Yeah, I was on master, my bad. I will try using the branch with a fix today.

**Comment by micorix** [comment]
Also ad DB config, we probably are gonna use Cockroach Cloud (generous free tier, even better than supabase).

Afaik cockroach DB is compatible with Postgres so the change shouldn't affect us much.

**Comment by micorix** [comment]
I managed to regenerate the db. Closing
