### ISSUE TITLE
Switch from Postgres to CockroachDB

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#32]
1. Use Cockroach adapter for database. 
2. Replace postgres with cockroach in docker-compose 

@Anakin100100 please specify ETA

**Comment by Anakin100100** [comment]
We will be unable to switch from postgres to cockroachdb due to lack of support for our version of the framework. Cockroach db adaper supports rails version 6.1.X and all the bundled gems (we are concerned mailny about ActiveRecord). The last supported version is rails 6.1.X. Unfortunetely they don't support the versions 7.X. The cockroachdb gem is not very popular (only 341,366 all time downloads) compared to postgres (179,409,413 all time downloads). This lack of community support would make it hard to debug any issues related to the database connection.

**Comment by Anakin100100** [comment]
Cocroachdb uses postgres protocol but is not the same thing. As the docs state "Although CockroachDB uses the PostgreSQL wire protocol and acts a lot like PostgreSQL, it’s very important to remember [CockroachDB ain’t PostgreSQL](https://www.cockroachlabs.com/blog/why-postgres). You can use CockroachDB as if it were PostgreSQL in a lot of places which means you won’t have to learn a bunch of new stuff to use it. But you might run into small differences in behavior like this." 

I don't think this is a good idea to switch databases like that especially when our search engine uses postgres specifically. We are likely to find weird bugs that result from these differences and debugging them is going to be really hard.  

I really appreciate your considerate forethought but I don't think that there is a compelling business case to switch to cockroachdb. I really like the idea of cockroachdb serverless but lack of compatibility and support for rails makes it an unforvarable choice of technology. The compatibility with postgres occurs at lover level but does not extend to our ORM and search engine. If I was designing a python app I would chose it because of premium supports for the latest version of django ORM.

The database does not use very much resources and I don't think there is a lot of real life improvements and costs saving resulting from such a change. @micorix what would you list as main advantages of using Cockroachdb as compared to postgres?

**Comment by Anakin100100** [comment]
This ruby app uses an older version of the ORM. They don't have too many resources allocated to rails because this version of the framework was in the making for more than a year and in porduction for more than half a year.

**Comment by micorix** [comment]
I'm not too attached to Cockroach. It's just they offer 5GB of storage compared to 500MB of storage offered by Supabase. Moreover this quota needs to cover both prod db and test one. If you are convinced that we won't hit 250MB in foreseeable future, let's stick with Supabase.

**Comment by Anakin100100** [comment]
I'm convinced that we won't hit 250 mb on a single database any time soon.

**Comment by micorix** [comment]
Ok, great! Closing this.
