### ISSUE TITLE
[umbrella issue] /search endpoint

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#46]
### Reasoning
Rn /institutions endpoint returns all data about schools we have. We don't need to fetch so many info we don't present to the user.

### What data do we need in search view?
* `id`
* `name`
* `foreignLanguages`
* `classProfiles`
* `rspoInstitutionTypeId`
* `public`
* `street`
* `buildingNo`
* `town`
* `latitude`
* `longitude`

#### We show too many schools
Please consider adding filter for `rspoInstitutionTypeId` or removing non-relevant institutions from db altogether like u suggested.
We only care rn about high schools, vocational schools and technical schools.

#### Pagination issue
eg. https://po8klasie.pl/api/institutions/?name_query=żerom returns:
```
{"results":[],"page":1,"totalItems":9936}
```
even though results length is clearly 0. totalItems` should be count of items considering filters (not on given page, but in general).

#### Fuzzy search threshold
:fire: high prio

IMO fuzzy search is too strict. 

examples:
* https://po8klasie.pl/api/institutions/?name_query=żerom should return the same things as ttps://po8klasie.pl/api/institutions/?name_query=%C5%BCeromskiego.
* https://po8klasie.pl/api/institutions/?name_query=hoff, https://po8klasie.pl/api/institutions/?name_query=hoffmanowa should return same results as https://po8klasie.pl/api/institutions/?name_query=hoffmanowej

**Comment by micorix** [comment]
please provide ETA

**Comment by Anakin100100** [comment]
Some non essential institution types have been removed and the number of institution records in the database fell from 11500 to 8700.

The bug with showing the absolute number of Institution records instead of only ones that match the search parameters has been removed. 

I don't know if you have the correct version of the api in production. It seems as though the version deployed there is from before the fuzzy search introduction. Locally the name search "żerom" returns 22 records while the full query "żeromskiego" returns 33 records. 

It seems like neither the gem that implements the fuzzy search nor the underlying postgres extension supports sensitivity changes for fuzzy search. The raw postgres function accepts only the text as input and sensitivity is not mentioned in the postgres docs.

**Comment by Anakin100100** [comment]
When it comes to fields that are redundant for the search view only the rspoInstitutionTypeId seems to be not required as of now. If some elements of the search view were removed they could be ommited from the api response but for now it's not the case. I don't think trying to optimize overfetching by one integer field is worth the time it would take to implement it on the frontend considering that we want to release it as soon as possible.

**Comment by Anakin100100** [comment]
@micorix have all your concerns with regard to the /search endpoint been properly addressed?

**Comment by micorix** [comment]
Yeah, but i'm not closing this issue fn, bc i'm still fighting with configuring db

**Comment by Anakin100100** [comment]
Can you describe the issue in more detail? It would be much easier for me to help you deal with it if I had a developer account on gcp instead of trying to give you a fix for an issue that is most probably resulting from another issue that I can't see from here.

**Comment by Anakin100100** [comment]
We communicated outside of Github and resolved the Supabase issue. Protip: when using extensions on supabase the way to enbale them is to do it manually in the UI.
