### ISSUE TITLE
Integrate backend with data from Gdynia open-data portal

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#5]
For now data will be provided by a test server to allow adjusting columns. Later, data will be sourced from Gdynia open-data production server.

Schools dataset with column mapping is available at http://ckan.monalisalabs.com/pl/dataset/szkoly (test server).

Please mind, that you can use CKAN (data CMS) API to retrieve when given resource were created and modified.
You can use `api/3/action/package_show?id=<id>` endpoint for that.
CKAN API docs: http://docs.ckan.org/en/2.9/api/

**Comment by micorix** [comment]
URLs we can query:
https://edukacja.gdynia.pl/api/schools/
https://edukacja.gdynia.pl/api/schools/indicators/

But these endpoints serve test data for now

**Comment by Anakin100100** [comment]
@wojtodzio I looked at this data and there doesn't seem to be any foreign key that we could join on except the phone number. Using the phone number as a foreign key is quite problematic because it changes with time and when it changes we no longer know which one is right. We could also search based on the combination of longitude and latitude because they should have been copied from the RSPO api.

**Comment by wojtodzio** [comment]
I agree, depending on the phone number does not sound like a good idea. The geographical position is probably more stable, although it can change as well, as schools can sometimes move to another location (even the high school I attended to did in the past 😉).
@micorix What do you think?

**Comment by micorix** [comment]
I will ask data provider to add RSPO ID column to the dataset but IMO it is not urgent bc for schools in Gdynia we will use exclusively data provided by Gdynia. So there is no need for joining this data with RSPO data.

**Comment by Anakin100100** [comment]
YYY, this needs to be discussed further because I'm sceptical about having a dedicated database table with only for schools from Gdynia. This introduces a lot of unnecessary complexity and potential bugs. I'd much rather lean towards treating the RSPO data as a main source of truth to be used for searching and filtering and the data from Gdynia would be used only to render extra info once a single school page is shown. The main table would only have a field boolean field has_extra_data_from_gdynia. When someone would click on a separate school page only then would the extra data be lazy loaded from a separate api call. The kinds of data provided by Gdynia are quite obscure to students and it would be confusing to include them in the main search and filtering tool. This data will be provided only for a very small percentage of schools and it shouldn't be our main priority. Extracting data for the matura examinations and added educational value is much more universal and meaningful to students. @wojtodzio what do you think about it?

**Comment by wojtodzio** [comment]
I agree, having a separate table just for Gdynia will increase the complexity and make it way harder to scale.
I assumed we'd instead create our data model based on our needs and then populate that model with data from whichever providers we can use. Since RSPO is available for all cities (is that assumption correct?), columns mapped from RSPO would always be present, and other columns would probably be optional, based on the available providers.

In other words, in my mind, we want something like that (pseudocode):
```
gdynia_lo_5 = Model.new(
  name:              rspo[gdynia][5].school_name,
  number_of_classes: gdynia_city_provider[5].number_of_classes,
  ...
)
warsaw_lo_5 = Model.new(
  name:              rspo[warsaw][5].school_name,
  number_of_classes: warsaw_city_provider[5].number_of_classes,
  ...
)
bielsko_lo_5 = Model.new(
  name:              rspo[bielsko][5].school_name,
  number_of_classes: custom_scraper_for_bielsko[5].number_of_classes,
  ...
)
bialystok_lo_5 = Model.new(
  name:              rspo[bialystok][5].school_name,
  number_of_classes: csv_for_bialystok[5].number_of_classes,
  ...
)
sosnowiec_lo_5 = Model.new(
  name:              rspo[sosnowiec][5].school_name,
  number_of_classes: null, # no data available :/
  ...
)
```
So no custom tables for each city, but custom providers and mappings, and a well-thought-out data model based on our needs (that's where we'll need @micorix help, as he knows which data is necessary for the frontend to work).
What do you think @Anakin100100 @micorix?

**Comment by micorix** [comment]
Ok, a few things from me. 
1. Data from Gdynia is absolutely crucial for us. IK that it would be easier to fetch data from SIO and then add lacking data from Gdynia but:
* Gdynia will include all data we need in their datasets. They also claim that they data is more up-to-date then data from Ministry of Edu. Gdynia is our partner and we should primarily take their data. We can also ask them to add columns we need.
* It doesn't matter if schools from Gdynia are roughly 2% of all schools we might have. For this year we will support Gdynia and Warsaw while focusing on Gdynia.
2. I'm a bit confused coz AFAIR we're gonna stick with generic model for all data. 

@Anakin100100 pls lmk what you think, but we SHOULD prioritize data from Gdynia.

Last minute update: Gdynia dataset has just been updated. Rspo IDs were added

**Comment by Anakin100100** [comment]
Ok we can prioretise this data if it is crucial for the project rollout. When it comes to where to put the extra data from Gdynia the main question is whether it will be required for filtering and this is really up to you. @micorix are we going to be doing filtering on this data?

**Comment by Anakin100100** [comment]
They responded and took action surprisingly fast for a government ran institution. Am I missing something or is their [api](https://edukacja.gdynia.pl/api/schools/?format=json) still down?

**Comment by wojtodzio** [comment]
I think we should start by defining our generic data model, i.e., deciding which data we'll always need and which we can optionally use. With that, we'll be able to determine what we can use from Gdynia's API and what we need from RSPO. I'm pretty sure there'll be a lot of data that we can just ignore (like the stuff salaries @Anakin100100 mentioned).
If we do that right, we won't have to handle Gdynia in any special way, except mapping their model to ours.

@Anakin100100 @micorix, would you guys be available tomorrow at 4:30 PM to discuss that?

**Comment by Anakin100100** [comment]
sure

**Comment by Anakin100100** [comment]
@wojtodzio @micorix Can we meet at 7pm. ? My vaccination date has been moved to today and I'm not going to be available at 4:30pm.

**Comment by wojtodzio** [comment]
7 pm works for me, but I'll have only 30 min

**Comment by Anakin100100** [comment]
Let's meet a little bit earlier then. Would 6:15 work for you?

**Comment by micorix** [comment]
Hi. Sorry, it just turned out that I'll not be available till 9 pm. But I think I can read notes from the meeting and follow up later. Would that be ok?

**Comment by Anakin100100** [comment]
I guess it's ok because defining the data model is mostly a backend issue. We would like you to get started on the data filtering strategy because this would be our next priority after we integrate the data from Gdynia. After that we could start thinking about the mvp

**Comment by wojtodzio** [comment]
Actually, @micorix probably knows the scope of the project the best, and I think your input would be very useful when designing our data model. I'd also want to address how we describe tasks, as I feel we don't communicate very efficiently right now, and I'd want to include both of you in that discussion.
Would 4:30 pm tomorrow work for you?

**Comment by Anakin100100** [comment]
yes

**Comment by Anakin100100** [comment]
@micorix I noticed that for some records from Gdynia the "rspo" field is empty. Will this be addressed will it be left as is? This issue affects some 35% of records .

**Comment by micorix** [comment]
@wojtodzio 4:30 pm works for me.

@Anakin100100 I'll look into this and ask the data provider if necessary.

**Comment by Anakin100100** [comment]
@wojtodzio @micorix 
This is the fields description of the extra data from Gdynia 
kod,nazwa,komentarz,opis,ikona,jednostka,okres,ostatnia_aktualizacja
"w92","Liczba etatów przypadających na jednego nauczyciela","","Liczba pełnowymiarowych etatów przypadających na jednego nauczyciela","people","",month,01-2022
"w110","Nauczyciele wspomagający","","Liczba nauczycieli wspomagających zatrudnionych w szkole","supervisor_account","os.",month,01-2022
"w161","Uczniowie pochodzący spoza Gdyni","","Porównanie liczby uczniów pochodzących z Gdyni z uczniami spoza Gdyni","location_city","%",year,2022
"w51","Klasy integracyjne","","Określenie występowania klas integracyjnych w szkołach","accessible","",year,2022
"wx1","Aktualny dzienny koszt oświaty","","Koszt działalności wszystkich szkół w dniu dzisiejszym","monetization_on","zł",year,2022
"wx2","Liczba sal lekcyjnych","","Liczba wszystkich sal lekcyjnych","domain","",year,2022
"wx3","Oddziały sportowe","","Liczba oddziałów sportowych","fitness_center","",year,2022
"w68","Zmianowość","","Określenie zmianowości","access_time","",month,01-2022
"w88","Liczba uczniów na nauczyciela","","Liczba uczniów przypadająca na jednego nauczyciela","supervisor_account","os.",year,2022

I think we are intersted in the following fields: "w51", "wx2", "wx3", "w68", "w88"
