### ISSUE TITLE
Add Swagger for the API

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#9]
Adding a Swagger may seem less work than keeping API docs in the repo

**Comment by micorix** [comment]
Another cool thing about setting up Swagger is that we can autogenerate TypeScript types from OpenAPI schema

**Comment by Anakin100100** [comment]
@micorix  I don't think this feature is too relevant because we really have one type that you can create from database schema (located in db/schema.rb). So far working with rswag hasn't been too great to say the least. So far I'm stuck and don't really know what to do. The documentation for automatically creating swagger files (rswag) is quite poor and the tool is really unituituve. Maybe Wojtek will figure something out because I'm out ideas.

**Comment by Anakin100100** [comment]
@micorix We managed together with @wojtodzio to debug this and we got rswag to work. We will convert the api integration tests to rswag soon but it's not very urgent.

**Comment by Anakin100100** [comment]
@micorix can we close this issue? My experience working with rswag so far has been negative. Using it would require rewriting our end to end tests using rswag specific dsl which is hard to work with and poorly documented. I don't see a lot of benefit to using swagger in general now and in the foreseeable future.

**Comment by micorix** [comment]
Yeah, let's close it for now. When we need swagger badly we'll reopen this issue
